### ISSUE TITLE
cut off the output after 50 lines

### ISSUE THREAD

**Issue by lindenksv** [steve-downing/OpenSorcerer#8]
Right now, I get some files in here that I have to scroll and scroll and scroll through. Can you just cut off any file at 50 lines? Very unlikely I find anything useful that far in and if it cuts something off, then at least I know to go look at that.

**Comment by lindenksv** [comment]
Oh and just finding the next set of "+++" doesn't work - it sends me to the last set of ++++ that I found via the finder, not to the next set after where I am in the document.

**Comment by steve-downing** [comment]
That makes sense. What about situations where a file is under two licenses? The first one could take up all 50 lines, leaving you not knowing that there's a second license.

**Comment by lindenksv** [comment]
That's fine. I'll take that tradeoff. I'll be able to tell if what i'm looking at is incomplete and then go pull the file. But all the extra scrolling is really killing the efficiency gains of this system.

**Comment by lindenksv** [comment]
If you can fix this today....that would be most awesome.

**Comment by steve-downing** [comment]
I may be able to fix it on the airplane in a few hours.

**Comment by lindenksv** [comment]
If we wanted to get fancy, then you could exempt files with the words "contribution" "license" "notice" "copyright" "readme" "about" "info" "third party" "copying"

**Comment by steve-downing** [comment]
If you're comfortable with that, I can make it happen, although that's probably a separate ticket

**Comment by steve-downing** [comment]
Done -- shipping you the new version now.
